import React, { useState, useRef, useEffect } from 'react';
import { gsap } from 'gsap';
import { ChatCircle, X, PaperPlaneTilt, Robot } from 'phosphor-react';

// Get Groq API key from environment variable
const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY || '';

const Chatbot: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [message, setMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [messages, setMessages] = useState([
    {
      id: 1,
      text: "Hi! I'm Sarweshwar's AI assistant. Ask me anything about his portfolio, skills, projects, or experience!",
      isBot: true,
      timestamp: new Date()
    }
  ]);

  const chatboxRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const robotRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Initial button animation
  useEffect(() => {
    gsap.fromTo(buttonRef.current,
      { scale: 0, rotation: -180 },
      { scale: 1, rotation: 0, duration: 1, delay: 2, ease: "back.out(1.7)" }
    );
  }, []);

  // Chatbox open animation
  useEffect(() => {
    if (isOpen) {
      gsap.fromTo(chatboxRef.current,
        { opacity: 0, scale: 0.8, y: 20 },
        { opacity: 1, scale: 1, y: 0, duration: 0.3, ease: "back.out(1.7)" }
      );
    }
  }, [isOpen]);

  // Waving robot animation
  useEffect(() => {
    if (robotRef.current) {
      gsap.to(robotRef.current, {
        rotation: 15,
        duration: 0.3,
        repeat: -1,
        yoyo: true,
        ease: "power1.inOut",
        transformOrigin: "bottom center"
      });
    }
  }, []);

  const toggleChat = () => {
    if (isOpen) {
      gsap.to(chatboxRef.current, {
        opacity: 0,
        scale: 0.8,
        y: 20,
        duration: 0.2,
        onComplete: () => setIsOpen(false)
      });
    } else {
      setIsOpen(true);
    }
  };

  // Minimal system prompt - let Groq answer based on general knowledge and user questions
  const systemPrompt = `You are Sarweshwar's portfolio assistant chatbot.

RULES:
- ONLY answer questions about Sarweshwar's portfolio .
- If asked about anything unrelated to the portfolio, politely say: "I can only answer questions about Sarweshwar's portfolio. Please ask about his skills, projects, experience, or contact information."
- Be concise, professional, and helpful
- Answer based on the context of a portfolio website for an AI/ML engineer in a structured manner in format of bullet points.

You can answer questions about:
- Technical skills and expertise
- Projects and work
- Professional experience
- Education background
- Certifications
- Contact information
- Career goals and interests

Do NOT answer:
- General knowledge questions
- Coding help or tutorials
- Unrelated topics
`;

  const handleSendMessage = async () => {
    if (!message.trim()) return;

    const newUserMessage = {
      id: messages.length + 1,
      text: message,
      isBot: false,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, newUserMessage]);
    const userQuery = message;
    setMessage('');
    setIsLoading(true);

    try {
      // Call Groq API with LLM for DYNAMIC response generation
      // NOT predefined responses - AI generates answers based on portfolio context
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${GROQ_API_KEY}`
        },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile', // Groq's fast LLM
          messages: [
            {
              role: 'system',
              content: systemPrompt // Minimal system prompt
            },
            {
              role: 'user',
              content: userQuery // User's question
            }
          ],
          temperature: 0.7, // Creativity level
          max_tokens: 500, // Response length
          top_p: 0.9,
          stream: false
        })
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        console.error('Groq API Error:', errorData);
        throw new Error(`API Error: ${response.status}`);
      }

      const data = await response.json();

      // Extract AI-generated response (NOT predefined!)
      const aiReply = data.choices[0]?.message?.content || "Sorry, I couldn't process that. Please try again.";

      const botResponse = {
        id: messages.length + 2,
        text: aiReply, // This is dynamically generated by Groq LLM
        isBot: true,
        timestamp: new Date()
      };

      setMessages(prev => [...prev, botResponse]);
    } catch (error) {
      console.error('Error calling Groq API:', error);

      const errorResponse = {
        id: messages.length + 2,
        text: "I'm having trouble connecting to the AI right now. Please check if your API key is set correctly in the .env file and try again!",
        isBot: true,
        timestamp: new Date()
      };

      setMessages(prev => [...prev, errorResponse]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50">
      {/* Waving Robot "Hi" Animation */}
      {!isOpen && (
        <div className="absolute -top-20 right-0 flex items-center gap-2 bg-gradient-to-r from-primary/20 to-secondary/20 backdrop-blur-md border border-white/10 rounded-2xl px-4 py-2 shadow-lg">
          <div ref={robotRef} className="text-3xl">
            👋
          </div>
          <span className="text-white font-semibold text-lg">Hi!</span>
        </div>
      )}

      {isOpen && (
        <div ref={chatboxRef} className="mb-4 w-80 h-96 glass-card overflow-hidden flex flex-col bg-black border-1 border-gray-200 rounded-2xl shadow-2xl">
          <div className="p-4 border-b border-glass-border bg-gradient-to-r from-primary/10 to-secondary/10">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-gradient-primary rounded-full animate-pulse">
                  <Robot size={20} className="text-foreground" />
                </div>
                <div>
                  <h3 className="font-semibold text-sm">AI Assistant</h3>
                  <p className="text-xs text-muted-foreground">Portfolio Expert</p>
                </div>
              </div>
              <button onClick={toggleChat} className="p-1 hover:bg-muted/20 rounded-full transition-colors">
                <X size={16} />
              </button>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map((msg) => (
              <div key={msg.id} className={`flex ${msg.isBot ? 'justify-start' : 'justify-end'}`}>
                <div
                  className={`max-w-xs px-3 py-2 rounded-lg text-sm ${msg.isBot
                    ? 'bg-muted/20 text-foreground'
                    : 'bg-gradient-primary text-foreground'
                    }`}>
                  {msg.text}
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex justify-start">
                <div className="max-w-xs px-3 py-2 rounded-lg text-sm bg-muted/20 text-foreground">
                  <div className="flex space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                    <div className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                    <div className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className="p-4 border-t border-glass-border">
            <div className="flex space-x-2">
              <input
                type="text"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Ask about portfolio..."
                disabled={isLoading}
                className="flex-1 px-3 py-2 bg-glass border border-glass-border rounded-lg text-sm focus:outline-none focus:border-primary disabled:opacity-50"
              />
              <button
                onClick={handleSendMessage}
                disabled={isLoading}
                className="p-2 w-8 h-8 bg-gradient-primary rounded-lg hover:scale-105 transition-transform disabled:opacity-50 disabled:cursor-not-allowed">
                <PaperPlaneTilt size={16} />
              </button>
            </div>
          </div>
        </div>
      )}

      <button ref={buttonRef} onClick={toggleChat} className="chatbot w-16 h-16 bg-gradient-primary rounded-full flex items-center justify-center shadow-glow-primary hover:scale-110 transition-transform">
        {isOpen ? (
          <X size={24} className="text-foreground" />
        ) : (
          <ChatCircle size={24} className="text-foreground" />
        )}
      </button>
    </div>
  );
};

export default Chatbot;